# Generated by Django 4.1.2 on 2024-09-24 19:45

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shows', '0012_alter_show_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date', models.DateField(verbose_name='date filled out')),
                ('receipts', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='%Y-%m-%d'), size=None)),
                ('completed', models.BooleanField(default=False, verbose_name='completed')),
                ('show', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='show', to='shows.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
