# Generated by Django 4.1.2 on 2024-09-24 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0012_alter_show_rate'),
        ('reimbs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reimbursement',
            name='receipts',
        ),
        migrations.RemoveField(
            model_name='reimbursement',
            name='user',
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reimbs', to='shows.member'),
        ),
    ]
