# Generated by Django 4.1.2 on 2024-09-25 15:43

import django.contrib.postgres.fields
from django.db import migrations, models
import reimbs.models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbs', '0002_remove_reimbursement_receipts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='receipts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=reimbs.models.get_upload_name), null=True, size=None),
        ),
    ]
