# Generated by Django 4.1.2 on 2024-10-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbs', '0004_alter_reimbursement_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reimbursement',
            name='receipts',
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date filled out'),
        ),
    ]
