# Generated by Django 4.1.2 on 2024-10-06 17:21

import django.contrib.postgres.fields
from django.db import migrations, models
import reimbs.models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbs', '0005_remove_reimbursement_receipts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='receipt',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=reimbs.models.get_upload_name), null=True, size=None),
        ),
    ]
