# Generated by Django 4.1.2 on 2024-10-09 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbs', '0006_reimbursement_description_reimbursement_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reimbursement',
            old_name='receipt',
            new_name='receipts',
        ),
    ]
