# Generated by Django 4.1.2 on 2024-10-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbs', '0007_rename_receipt_reimbursement_receipts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
