# Generated by Django 4.1.2 on 2024-10-23 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reimbs', '0009_remove_reimbursement_receipts_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='receipt',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='reimb',
        ),
        migrations.CreateModel(
            name='ReceiptList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reimb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='reimbs.reimbursement')),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='reimbs.receiptlist'),
        ),
    ]
