# Generated by Django 4.1.2 on 2024-10-25 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reimbs', '0010_rename_receipt_receipt_image_remove_receipt_reimb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptlist',
            name='reimb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='reimbs.reimbursement'),
        ),
    ]
