# Generated by Django 4.1.2 on 2024-10-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reimbs', '0011_alter_receiptlist_reimb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptlist',
            name='reimb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_list', to='reimbs.reimbursement'),
        ),
    ]
