FROM python:3.9 as frontend_base
    # Install curl, node, & yarn
    RUN apt-get -y install curl \
      && curl -sL https://deb.nodesource.com/setup_16.x | bash \
      && apt-get -y install nodejs \
      && curl -o- -L https://yarnpkg.com/install.sh | bash

FROM python:3.9 as backend_base
    WORKDIR /app/backend

    # Install Python dependencies
    COPY ./backend/requirements.txt /app/backend/
    RUN pip3 install --upgrade uv

from frontend_base AS frontend_setup
    # Install JS dependencies
    WORKDIR /app/frontend

    COPY ./frontend/package.json ./frontend/yarn.lock /app/frontend/
    RUN $HOME/.yarn/bin/yarn install

FROM backend_base AS backend_setup
    RUN uv pip install -r requirements.txt

FROM frontend_setup AS app_setup
    COPY --from=backend_setup . .
    # Add the rest of the code
    COPY . /app
    COPY ./backend/scripts/ /app/

    # Build static files
    RUN $HOME/.yarn/bin/yarn build

    # Have to move all static files other than index.html to root/
    # for whitenoise middleware
    WORKDIR /app/frontend/build

    RUN mkdir root && mv *.ico *.json root

    # Collect static files
    RUN mkdir /app/backend/staticfiles

FROM app_setup AS finish_setup
    WORKDIR /app

    RUN DJANGO_SETTINGS_MODULE=core.settings.prod \
        python3 backend/manage.py collectstatic --noinput

    EXPOSE $PORT

    RUN ["chmod", "+x", "/app/entrypoint-prod.sh"]
    ENTRYPOINT ["/app/entrypoint-prod.sh"]

