# Generated by Django 4.1.2 on 2026-01-18 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shows', '0007_alter_show_payment_method_alter_show_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=150)),
                ('user_last_name', models.CharField(max_length=150)),
                ('show_name', models.CharField(max_length=150)),
                ('show_date', models.DateField()),
                ('photo_url', models.URLField()),
                ('notes', models.TextField(blank=True)),
                ('payment_method', models.PositiveSmallIntegerField(choices=[(0, 'Venmo'), (1, 'Zelle')])),
                ('payment_username', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to='shows.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
