# Generated by Django 4.1.2 on 2024-08-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0008_show_paid_alter_show_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
    ]
