# Generated by Django 4.1.2 on 2026-01-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0008_reimbursement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='show_name',
            field=models.CharField(max_length=60),
        ),
    ]
