# Generated by Django 4.1.2 on 2024-08-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0009_alter_show_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='paid',
        ),
        migrations.AlterField(
            model_name='show',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='rate'),
        ),
    ]
