# Generated by Django 4.1.2 on 2026-01-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0009_alter_reimbursement_show_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='photo_url',
            field=models.URLField(max_length=500),
        ),
    ]
