# Generated by Django 4.1.2 on 2026-02-03 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0010_alter_reimbursement_photo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reimbursement',
            old_name='photo_url',
            new_name='receipt_url',
        ),
    ]
