# Generated by Django 4.1.2 on 2024-08-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0011_show_paid_alter_show_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Show Fee'),
        ),
    ]
