# Generated by Django 4.1.2 on 2024-10-02 17:08

from django.db import migrations, models
import django.db.models.deletion
import receipts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reimbs', '0005_remove_reimbursement_receipts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.ImageField(upload_to=receipts.models.get_upload_name)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reimbs.reimbursement')),
            ],
        ),
    ]
