# Generated by Django 4.1.2 on 2026-01-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='venmo_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='zelle_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
