# Generated by Django 4.1.2 on 2026-01-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_venmo_username_user_zelle_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='venmo_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='zelle_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
