name: Heroku Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'culd-hub'
          heroku_email: 'ew2664@columbia.edu'
          usedocker: true
          docker_build_args: |
            SLACK_TOKEN_ARG
        env:
          SLACK_TOKEN_ARG: ${{secrets.SLACK_TOKEN_ENV}}