name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Pylint
        working-directory: ./backend
        run: |
          pylint --disable=C0114,C0115,C0116,R0903,W0613  --fail-under=8.5 --ignore=migrations --msg-template="$FileDir$/{path}:{line}:{column}:{C}:({symbol}){msg}" --load-plugins=pylint_django --django-settings-module=core.settings $(git ls-files '*.py')
      - name: Make Migrations
        working-directory: ./backend
        run: |
          python manage.py makemigrations
          python manage.py migrate
      - name: Run Unit Tests
        working-directory: ./backend
        run: |
          coverage run manage.py test
          coverage xml
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          version: "v0.1.15"
